### ISSUE TITLE
will you release it? or selling it?

### ISSUE THREAD

**Issue by ONyambura** [Zapherion/TB-Core#1]
will you release it? or selling it?

**Comment by Zapherion** [comment]
We're not sure yet. Will keep you updated.

**Comment by ONyambura** [comment]
i would like to buy it too if youre up!


Στις Σάβ, 12 Οκτ 2019 στις 12:40 π.μ., ο/η Teun <notifications@github.com>
έγραψε:

**Comment by Zapherion** [comment]
In this stage the framework wouldn't be playable. You can follow the updates on our discord. Keep in mind that most of it is in dutch. https://invite.gg/tbcorenl

**Comment by ONyambura** [comment]
just joined on discord , could you send me a dm please?

Nyambura#1976

Στις Σάβ, 12 Οκτ 2019 στις 4:34 μ.μ., ο/η Teun <notifications@github.com>
έγραψε:
